---
- name: Add GPG key
  apt_key: url=https://repo.varnish-cache.org/ubuntu/GPG-key.txt

- name: Add Varnish URL to sources.list
  apt_repository: repo='deb http://repo.varnish-cache.org/ubuntu/ trusty varnish-3.0' update_cache=yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- name: Install Varnish 3.0
  apt: pkg=varnish state=latest update_cache=yes
  
- name: Open access to the reverse proxy
  ufw: rule=allow port={{ reverse_proxy_port }}

- name: Create /etc/varnish/wordpress.vcl
  template: src=wordpress.vcl.j2 dest=/etc/varnish/wordpress.vcl backup=yes owner=root group=root mode=0644
  notify: Restart Varnish

- name: Change /etc/default/varnish
  template: src=varnish.j2 dest=/etc/default/varnish backup=yes owner=root group=root mode=0644
  notify: Restart Varnish
